<?php
require_once('inc/open_conn.php');
$uId = $_GET['uId'];
$strSql = "DELETE FROM cat_users WHERE intId = " . $uId . ";";
echo $strSql . "<br />";
mysql_query($strSql);
$strSql = "DELETE FROM tbl_usr_activity WHERE intUser1 = " . $uId . ";";
echo $strSql . "<br />";
mysql_query($strSql);
$strSql = "DELETE FROM tbl_usr_activity WHERE intUser2 = " . $uId . ";";
echo $strSql . "<br />";
mysql_query($strSql);
$strSql = "DELETE FROM tbl_usr_comments WHERE intUser = " . $uId . ";";
echo $strSql . "<br />";
mysql_query($strSql);
$strSql = "DELETE FROM tbl_usr_friendship WHERE intUser = " . $uId . ";";
echo $strSql . "<br />";
mysql_query($strSql);
$strSql = "DELETE FROM tbl_usr_friendship WHERE intFriend = " . $uId . ";";
echo $strSql . "<br />";
mysql_query($strSql);
$strSql = "DELETE FROM tbl_usr_settings WHERE intUser = " . $uId . ";";
echo $strSql . "<br />";
mysql_query($strSql);
$strSql = "DELETE FROM tbl_usr_stickers WHERE intUser = " . $uId . ";";
echo $strSql . "<br />";
mysql_query($strSql);
mysql_close($con);
require_once('inc/clearsess.php');
?>