<?php
require_once('inc/open_conn.php');
include('inc/func.php');
$arrEmailLang = getLangArray('EMAIL',$_POST['sLang']);
$strPhoto = urldecode($_POST['sPhoto']);
$strRegResponse = "";
$strSql = "INSERT INTO cat_users (strEmail,strPassword,strName,strLastName,strNick,strCity,strCountry,dteBirthday,intLevel,intPoints,intTime,intBBI,intFBId,strFBEmail,strFBScreenmail,strGender,strUsrPic,tmeRegDate,strUsrLang,intUsrType,intSessions,intuVals00,intuVals01,intuVals02,intuVals03,intuVals04) VALUES (";
$strSql .= "'" . urldecode(strtolower($_POST['sEmail'])) . "',";
$strSql .= "'" . urldecode(strtolower($_POST['sPwd'])) . "',";
$strSql .= "'" . urldecode(ucwords(strtolower($_POST['sName']))) . "',";
$strSql .= "'" . urldecode(ucwords(strtolower($_POST['sLastName']))) . "',";
$strSql .= "'" . urldecode(strtolower($_POST['sNName'])) . "',";
$strSql .= "'" . urldecode(ucwords(strtolower($_POST['sCity']))) . "',";
$strSql .= "'" . $_POST['sCountry'] . "',";
$strSql .= "'" . $_POST['sYear'] . "-" . $_POST['sMonth'] . "-" . $_POST['sDay'] . "',";
$strSql .= "0,";
$strSql .= "0,";
$strSql .= "0,";
$strSql .= "0,";
if($_POST['sFBId'] == ''){
	$strSql .= "NULL,";
	$strSql .= "NULL,";
	$strSql .= "NULL,";
}else{
	$strSql .= $_POST['sFBId'] . ",";
	$strSql .= "'" . urldecode($_POST['sFBEmail']) . "',";
	$strSql .= "'" . urldecode($_POST['sFBUserScreen']) . "',";
};
$strSql .= "'" . $_POST['sGender'] . "',";
$strPhoto = str_replace('url(','',$strPhoto);
$strPhoto = str_replace(')','',$strPhoto);
$strPhoto = str_replace('"','',$strPhoto);
$strPhoto = str_replace("'","",$strPhoto);
$strSql .= "'" . $strPhoto . "'";
$strSql .= ",NOW()";
$strSql .= ",'" . $_POST['sLang'] . "',1,0,20,20,20,20,20);";
mysql_query($strSql);
$strSql = "SELECT intId FROM cat_users WHERE strEmail = '" . $_POST['sEmail'] . "';";
$rstGetID = mysql_query($strSql);
$strRegResponse = mysql_result($rstGetID,0,0);
$strSql = "INSERT INTO tbl_usr_settings (";
$strSql .= "intUser,";
$strSql .= "intShare01,intShare02,intShare03,intShare04,intShare05,intShare06,";
$strSql .= "intPrivacy01,intPrivacy02,intPrivacy03,intPrivacy04,intPrivacy05,";
$strSql .= "intNotifications01,intNotifications02,intNotifications03,intNotifications04,intNotifications05,intNotifications06,intNotifications07,intNotifications08,intNotifications09,intNotifications10,intNotifications11,intNotifications12,intNotifications13,";
$strSql .= "intOthers01";
$strSql .= ") VALUES (" . $strRegResponse . ",1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);";
mysql_query($strSql);
$strSql = "INSERT INTO tbl_usr_activity (intType,intUser1,intRead,dteTimeStamp) VALUES (1," . $strRegResponse . ",0,NOW());";
mysql_query($strSql);
$to = strtolower($_POST['sEmail']);
$subject = str_replace("&&user&&",ucwords(strtolower($_POST['sName'])),$arrEmailLang['welcometobeebrite']);
$message = "<html>";
$message .= "<head>";
$message .= "<meta content='text/html; charset=utf-8' http-equiv='Content-Type'>";
$message .= "</head>";
$message .= "<body style=' background-color:#F0F0F0; font-family:Tahoma; font-weight:normal; color:#666666; margin:0px 0px 0px 0px; '>";
$message .= "<table style='margin:20px auto 0px auto;'>";
$message .= "	<tr><td colspan='2' style='text-align:center;'><img src='http://www.beebrite.com/img/email/header.png' alt='Beebrite' /></td></tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center;font-size:28px;'>" . $arrEmailLang['welcome_01'] . " ". ucwords(strtolower($_POST['sName'])) . "!</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center;font-size:13px;'>" . $arrEmailLang['welcome_02'] . "</td></tr>";
$message .= "	<tr><td colspan='2' style='height:40px;'>&nbsp;</td></tr>";
$message .= "	<tr>";
$message .= "		<td style='text-align:right'><img src='http://www.beebrite.com/img/email/welcome_01.png' alt='Beebrite' /></td>";
$message .= "		<td style='padding-left:20px;'>" . $arrEmailLang['welcome_03'] . "<span style='font-size:12px'><br />" . $arrEmailLang['welcome_04'] . "</span></td>";
$message .= "	</tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "	<tr>";
$message .= "		<td style='text-align:right; padding-right:20px;'>" . $arrEmailLang['welcome_05'] . "<span style='font-size:12px'><br />" . $arrEmailLang['welcome_06'] . "</span></td>";
$message .= "		<td><img src='http://www.beebrite.com/img/email/welcome_02.png' alt='Beebrite' /></td>";
$message .= "	</tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "	<tr>";
$message .= "		<td style='text-align:right'><img src='http://www.beebrite.com/img/email/welcome_03.png' alt='Beebrite' /></td>";
$message .= "		<td style='padding-left:20px;'>" . $arrEmailLang['welcome_07'] . "<span style='font-size:12px'><br />" . $arrEmailLang['welcome_08'] . "</span></td>";
$message .= "	</tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center'><a href='http://www.beebrite.com' style='height:50px; line-height:50px; text-decoration:none; background-color:#505050; border:1px solid #323232; border-radius:3px; padding:16px 15px 16px 15px; font-size:17px; color:#FFFFFF; box-shadow:inset 0px 0px 1px 1px rgba(255,255,255,0.5); margin:10px 0px 0px 0px; cursor:pointer;'>" . $arrEmailLang['welcome_09'] . "</a></td></tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center;font-size:17px;'>" . $arrEmailLang['footer_00'] . "</td></tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center'><a href='http://www.facebook.com/beebrite'><img src='http://www.beebrite.com/img/email/facebook.png' style='border:0px;'></a>&nbsp;<a href='https://twitter.com/beebrite_'><img src='http://www.beebrite.com/img/email/twitter.png' style='border:0px;'></a>&nbsp;<a href='http://pinterest.com/wearebeebrite/'><img src='http://www.beebrite.com/img/email/pinterest.png' style='border:0px;'></a></td></tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center;font-size:10px'>" . $arrEmailLang['footer_01'] . " " . strtolower($_POST['sEmail']) . "</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center;font-size:10px'>" . $arrEmailLang['footer_02	'] . " <a href='http://www.beebrite.com' style='color:#505050; font-weight:bold; text-decoration:none'>" . $arrEmailLang['footer_03'] . "</a></td></tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center;font-size:10px'>&copy;2012 Beebrite SL.&nbsp;|&nbsp;" . $arrEmailLang['footer_04'] . "</td></tr>";
$message .= "	<tr><td colspan='2' style='text-align:center;font-size:10px'><a href='http://www.beebrite.com' style='color:#505050; font-weight:bold; text-decoration:none'>" . $arrEmailLang['footer_05'] . "</a>&nbsp;|&nbsp;<a href='http://www.beebrite.com' style='color:#505050; font-weight:bold; text-decoration:none'>" . $arrEmailLang['footer_06'] . "</a></td></tr>";
$message .= "	<tr><td colspan='2' style='height:20px;'>&nbsp;</td></tr>";
$message .= "</table>";
$message .= "</body>";
$message .= "</html>";
$headers = "From: Beebrite <beebritebot@beebrite.com>\r\n";
$headers .= "Reply-To: beebritebot@beebrite.com\r\n";
$headers .= "MIME-Version: 1.0\r\n";
$headers .= "Content-type: text/html; charset=utf-8\r\n";
$mail_sent = @mail( $to, $subject, $message, $headers );
unset($arrEmailLang);
mysql_close($con);
echo $strRegResponse;
?>